INFO:root:Sent report alphacorp8.8.4.4: alphacorp8.8.4.4, ping test, 100, Status: 201, Time: 2024-11-08 17:07:21.480653
INFO:root:Sent report cloudgiant413.248.122.2: cloudgiant413.248.122.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:22.802127
INFO:root:Sent report fastdns2208.67.222.222: fastdns2208.67.222.222, ping test, 100, Status: 201, Time: 2024-11-08 17:07:31.890302
INFO:root:Sent report loopback2127.0.0.3: loopback2127.0.0.3, ping test, 100, Status: 201, Time: 2024-11-08 17:07:36.399758
INFO:root:Sent report linuxhub13127.0.8.13: linuxhub13127.0.8.13, ping test, 100, Status: 201, Time: 2024-11-08 17:07:37.159942
INFO:root:Sent report cloudgiant1213.248.130.2: cloudgiant1213.248.130.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:38.416740
INFO:root:Sent report techsoft13.107.43.16: techsoft13.107.43.16, ping test, 100, Status: 201, Time: 2024-11-08 17:07:38.488790
INFO:root:Sent report securecloud21.1.1.1: securecloud21.1.1.1, ping test, 100, Status: 201, Time: 2024-11-08 17:07:39.154275
INFO:root:Sent report loopback4127.0.0.5: loopback4127.0.0.5, ping test, 100, Status: 201, Time: 2024-11-08 17:07:39.398095
INFO:root:Sent report securecloud31.0.1.0: securecloud31.0.1.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:39.597124
INFO:root:Sent report nextgen9.9.9.10: nextgen9.9.9.10, ping test, 100, Status: 201, Time: 2024-11-08 17:07:39.609174
INFO:root:Sent report loopback6127.0.0.7: loopback6127.0.0.7, ping test, 100, Status: 201, Time: 2024-11-08 17:07:40.236444
INFO:root:Sent report loopback8127.0.0.9: loopback8127.0.0.9, ping test, 100, Status: 201, Time: 2024-11-08 17:07:40.661979
INFO:root:Sent report fastdns208.67.220.220: fastdns208.67.220.220, ping test, 100, Status: 201, Time: 2024-11-08 17:07:40.670979
INFO:root:Sent report linuxhub5127.0.8.5: linuxhub5127.0.8.5, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.021007
INFO:root:Sent report alphacorp28.8.8.8: alphacorp28.8.8.8, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.058431
INFO:root:Sent report linuxhub2127.0.8.2: linuxhub2127.0.8.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.330638
INFO:root:Sent report linuxhub4127.0.8.4: linuxhub4127.0.8.4, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.335638
INFO:root:Sent report loopback15127.0.0.16: loopback15127.0.0.16, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.370861
INFO:root:Sent report loopback3127.0.0.4: loopback3127.0.0.4, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.410297
INFO:root:Sent report fastdns3208.67.219.219: fastdns3208.67.219.219, ping test, 50, Status: 201, Time: 2024-11-08 17:07:41.626069
INFO:root:Sent report fastdns15208.67.207.207: fastdns15208.67.207.207, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.685670
INFO:root:Sent report nextgen29.9.9.9: nextgen29.9.9.9, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.689664
INFO:root:Sent report techsoft813.107.50.16: techsoft813.107.50.16, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.706097
INFO:root:Sent report techsoft1213.107.54.16: techsoft1213.107.54.16, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.721252
INFO:root:Sent report loopback5127.0.0.6: loopback5127.0.0.6, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.732250
INFO:root:Sent report loopback12127.0.0.13: loopback12127.0.0.13, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.792893
INFO:root:Sent report cloudgiant13.248.119.2: cloudgiant13.248.119.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.810923
INFO:root:Sent report loopback7127.0.0.8: loopback7127.0.0.8, ping test, 100, Status: 201, Time: 2024-11-08 17:07:41.994966
INFO:root:Sent report securecloud1.0.0.1: securecloud1.0.0.1, ping test, 100, Status: 201, Time: 2024-11-08 17:07:42.015850
INFO:root:Sent report cloudgiant1113.248.129.2: cloudgiant1113.248.129.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:42.622123
INFO:root:Sent report cloudgiant1413.248.132.2: cloudgiant1413.248.132.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:42.636991
INFO:root:Sent report linuxhub7127.0.8.7: linuxhub7127.0.8.7, ping test, 100, Status: 201, Time: 2024-11-08 17:07:42.966762
INFO:root:Sent report loopback13127.0.0.14: loopback13127.0.0.14, ping test, 100, Status: 201, Time: 2024-11-08 17:07:43.250638
INFO:root:Sent report alphacorp38.8.3.3: alphacorp38.8.3.3, ping test, 50, Status: 201, Time: 2024-11-08 17:07:43.243370
INFO:root:Sent report nextgen39.9.8.10: nextgen39.9.8.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:43.265129
INFO:root:Sent report cloudgiant1513.248.133.2: cloudgiant1513.248.133.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:43.294196
INFO:root:Sent report loopback9127.0.0.10: loopback9127.0.0.10, ping test, 100, Status: 201, Time: 2024-11-08 17:07:43.281569
INFO:root:Sent report techsoft413.107.46.16: techsoft413.107.46.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:43.380376
INFO:root:Sent report techsoft613.107.48.16: techsoft613.107.48.16, ping test, 100, Status: 201, Time: 2024-11-08 17:07:43.389614
INFO:root:Sent report skynet920.45.25.4: skynet920.45.25.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:43.577752
INFO:root:Sent report linuxhub12127.0.8.12: linuxhub12127.0.8.12, ping test, 100, Status: 201, Time: 2024-11-08 17:07:43.708549
INFO:root:Sent report alphacorp118.8.11.11: alphacorp118.8.11.11, ping test, 100, Status: 201, Time: 2024-11-08 17:07:43.905867
INFO:root:Sent report linuxhub15127.0.8.15: linuxhub15127.0.8.15, ping test, 100, Status: 201, Time: 2024-11-08 17:07:43.935594
INFO:root:Sent report loopback11127.0.0.12: loopback11127.0.0.12, ping test, 100, Status: 201, Time: 2024-11-08 17:07:43.957780
80
INFO:root:Sent report linuxhub10127.0.8.10: linuxhub10127.0.8.10, ping test, 100, Status: 201, Time: 2024-11-08 17:07:44.133667
67
INFO:root:Sent report linuxhub127.0.8.1: linuxhub127.0.8.1, ping test, 100, Status: 201, Time: 2024-11-08 17:07:44.150790
INFO:root:Sent report linuxhub14127.0.8.14: linuxhub14127.0.8.14, ping test, 100, Status: 201, Time: 2024-11-08 17:07:44.173041
INFO:root:Sent report cloudgiant213.248.120.2: cloudgiant213.248.120.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:44.322888
INFO:root:Sent report alphacorp48.8.2.2: alphacorp48.8.2.2, ping test, 50, Status: 201, Time: 2024-11-08 17:07:44.296129
INFO:root:Sent report nextgen49.9.7.10: nextgen49.9.7.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:44.359887
INFO:root:Sent report fastdns8208.67.214.214: fastdns8208.67.214.214, ping test, 50, Status: 201, Time: 2024-11-08 17:07:44.461530
INFO:root:Sent report linuxhub3127.0.8.3: linuxhub3127.0.8.3, ping test, 100, Status: 201, Time: 2024-11-08 17:07:44.483001
INFO:root:Sent report loopback14127.0.0.15: loopback14127.0.0.15, ping test, 100, Status: 201, Time: 2024-11-08 17:07:44.715559
INFO:root:Sent report skynet20.45.17.4: skynet20.45.17.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:44.726959
INFO:root:Sent report skynet520.45.21.4: skynet520.45.21.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:44.788363
INFO:root:Sent report fruittech917.253.145.19: fruittech917.253.145.19, ping test, 50, Status: 201, Time: 2024-11-08 17:07:45.300169
INFO:root:Sent report cloudgiant1313.248.131.2: cloudgiant1313.248.131.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:45.356464
INFO:root:Sent report cloudgiant713.248.125.2: cloudgiant713.248.125.2, ping test, 50, Status: 201, Time: 2024-11-08 17:07:45.447545
INFO:root:Sent report skynet320.45.19.4: skynet320.45.19.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:45.602210
INFO:root:Sent report fruittech217.253.145.12: fruittech217.253.145.12, ping test, 50, Status: 201, Time: 2024-11-08 17:07:45.653214
INFO:root:Sent report securecloud51.0.3.0: securecloud51.0.3.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:45.839978
INFO:root:Sent report cloudgiant513.248.123.2: cloudgiant513.248.123.2, ping test, 50, Status: 201, Time: 2024-11-08 17:07:45.869995
INFO:root:Sent report alphacorp58.8.1.1: alphacorp58.8.1.1, ping test, 100, Status: 201, Time: 2024-11-08 17:07:45.929345
INFO:root:Sent report techsoft713.107.49.16: techsoft713.107.49.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:46.150284
INFO:root:Sent report linuxhub6127.0.8.6: linuxhub6127.0.8.6, ping test, 100, Status: 201, Time: 2024-11-08 17:07:46.473435
INFO:root:Sent report loopback10127.0.0.11: loopback10127.0.0.11, ping test, 100, Status: 201, Time: 2024-11-08 17:07:46.552734
INFO:root:Sent report linuxhub11127.0.8.11: linuxhub11127.0.8.11, ping test, 100, Status: 201, Time: 2024-11-08 17:07:46.555731
INFO:root:Sent report nextgen79.9.4.10: nextgen79.9.4.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:46.556732
INFO:root:Sent report nextgen59.9.6.10: nextgen59.9.6.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:46.615656
INFO:root:Sent report securecloud81.0.6.0: securecloud81.0.6.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:46.772772
INFO:root:Sent report cloudgiant1013.248.128.2: cloudgiant1013.248.128.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:46.907990
INFO:root:Sent report nextgen99.9.2.10: nextgen99.9.2.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:47.122023
INFO:root:Sent report loopback127.0.0.2: loopback127.0.0.2, ping test, 100, Status: 201, Time: 2024-11-08 17:07:47.549883
INFO:root:Sent report nextgen89.9.3.10: nextgen89.9.3.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:47.732078
INFO:root:Sent report securecloud41.0.2.0: securecloud41.0.2.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:48.032531
INFO:root:Sent report fastdns9208.67.213.213: fastdns9208.67.213.213, ping test, 50, Status: 201, Time: 2024-11-08 17:07:48.035615
INFO:root:Sent report fruittech17.253.145.11: fruittech17.253.145.11, ping test, 50, Status: 201, Time: 2024-11-08 17:07:48.198271
INFO:root:Sent report linuxhub8127.0.8.8: linuxhub8127.0.8.8, ping test, 100, Status: 201, Time: 2024-11-08 17:07:48.382159
INFO:root:Sent report fruittech817.253.145.18: fruittech817.253.145.18, ping test, 50, Status: 201, Time: 2024-11-08 17:07:48.482857
INFO:root:Sent report alphacorp108.8.10.10: alphacorp108.8.10.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:48.613734
INFO:root:Sent report fastdns10208.67.212.212: fastdns10208.67.212.212, ping test, 50, Status: 201, Time: 2024-11-08 17:07:49.681107
INFO:root:Sent report techsoft513.107.47.16: techsoft513.107.47.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:49.979596
INFO:root:Sent report techsoft1513.107.57.16: techsoft1513.107.57.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:50.249139
INFO:root:Sent report techsoft313.107.45.16: techsoft313.107.45.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:50.259359
INFO:root:Sent report securecloud71.0.5.0: securecloud71.0.5.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:50.278794
INFO:root:Sent report fruittech1117.253.145.21: fruittech1117.253.145.21, ping test, 50, Status: 201, Time: 2024-11-08 17:07:50.743363
INFO:root:Sent report securecloud121.0.10.0: securecloud121.0.10.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:50.965819
INFO:root:Sent report fruittech1217.253.145.22: fruittech1217.253.145.22, ping test, 50, Status: 201, Time: 2024-11-08 17:07:50.983612
INFO:root:Sent report securecloud131.0.11.0: securecloud131.0.11.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:51.132309
INFO:root:Sent report alphacorp128.8.12.12: alphacorp128.8.12.12, ping test, 50, Status: 201, Time: 2024-11-08 17:07:51.269410
INFO:root:Sent report cloudgiant613.248.124.2: cloudgiant613.248.124.2, ping test, 50, Status: 201, Time: 2024-11-08 17:07:51.563786
INFO:root:Sent report fruittech717.253.145.17: fruittech717.253.145.17, ping test, 50, Status: 201, Time: 2024-11-08 17:07:51.698211
INFO:root:Sent report techsoft213.107.44.16: techsoft213.107.44.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:51.923311
INFO:root:Sent report fruittech1317.253.145.23: fruittech1317.253.145.23, ping test, 50, Status: 201, Time: 2024-11-08 17:07:51.971826
INFO:root:Sent report skynet620.45.22.4: skynet620.45.22.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:52.289130
INFO:root:Sent report skynet1120.45.27.4: skynet1120.45.27.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:53.080855
INFO:root:Sent report skynet1520.45.31.4: skynet1520.45.31.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:53.215903
INFO:root:Sent report skynet1020.45.26.4: skynet1020.45.26.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:53.453568
INFO:root:Sent report cloudgiant813.248.126.2: cloudgiant813.248.126.2, ping test, 50, Status: 201, Time: 2024-11-08 17:07:54.382119
INFO:root:Sent report skynet720.45.23.4: skynet720.45.23.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:54.672583
INFO:root:Sent report nextgen159.9.9.99: nextgen159.9.9.99, ping test, 50, Status: 201, Time: 2024-11-08 17:07:54.691568
INFO:root:Sent report securecloud141.0.12.0: securecloud141.0.12.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:54.888638
INFO:root:Sent report nextgen139.9.11.10: nextgen139.9.11.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:54.974014
INFO:root:Sent report securecloud151.0.13.0: securecloud151.0.13.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:55.168835
INFO:root:Sent report fruittech617.253.145.16: fruittech617.253.145.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:55.215974
INFO:root:Sent report fastdns14208.67.208.208: fastdns14208.67.208.208, ping test, 50, Status: 201, Time: 2024-11-08 17:07:55.592401
INFO:root:Sent report alphacorp98.8.5.5: alphacorp98.8.5.5, ping test, 50, Status: 201, Time: 2024-11-08 17:07:55.941360
INFO:root:Sent report nextgen149.9.10.10: nextgen149.9.10.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:56.039239
INFO:root:Sent report securecloud61.0.4.0: securecloud61.0.4.0, ping test, 50, Status: 201, Time: 2024-11-08 17:07:56.464738
INFO:root:Sent report alphacorp158.8.15.15: alphacorp158.8.15.15, ping test, 50, Status: 201, Time: 2024-11-08 17:07:56.845264
INFO:root:Sent report techsoft913.107.51.16: techsoft913.107.51.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:56.995516
INFO:root:Sent report techsoft1313.107.55.16: techsoft1313.107.55.16, ping test, 50, Status: 201, Time: 2024-11-08 17:07:57.196238
INFO:root:Sent report skynet420.45.20.4: skynet420.45.20.4, ping test, 50, Status: 201, Time: 2024-11-08 17:07:57.386244
INFO:root:Sent report fastdns11208.67.211.211: fastdns11208.67.211.211, ping test, 50, Status: 201, Time: 2024-11-08 17:07:57.639252
INFO:root:Sent report nextgen109.9.1.10: nextgen109.9.1.10, ping test, 50, Status: 201, Time: 2024-11-08 17:07:59.958512
INFO:root:Sent report fastdns12208.67.210.210: fastdns12208.67.210.210, ping test, 50, Status: 201, Time: 2024-11-08 17:08:00.193971
INFO:root:Sent report alphacorp138.8.13.13: alphacorp138.8.13.13, ping test, 50, Status: 201, Time: 2024-11-08 17:08:00.309715
INFO:root:Sent report nextgen119.9.0.10: nextgen119.9.0.10, ping test, 50, Status: 201, Time: 2024-11-08 17:08:00.341159
INFO:root:Sent report fruittech317.253.145.13: fruittech317.253.145.13, ping test, 50, Status: 201, Time: 2024-11-08 17:08:00.349619
INFO:root:Sent report techsoft1113.107.53.16: techsoft1113.107.53.16, ping test, 50, Status: 201, Time: 2024-11-08 17:08:00.470303
INFO:root:Sent report skynet1320.45.29.4: skynet1320.45.29.4, ping test, 50, Status: 201, Time: 2024-11-08 17:08:00.570952
INFO:root:Sent report alphacorp68.8.6.6: alphacorp68.8.6.6, ping test, 50, Status: 201, Time: 2024-11-08 17:08:01.043277
INFO:root:Sent report fruittech1417.253.145.24: fruittech1417.253.145.24, ping test, 50, Status: 201, Time: 2024-11-08 17:08:01.046458
INFO:root:Sent report skynet820.45.24.4: skynet820.45.24.4, ping test, 50, Status: 201, Time: 2024-11-08 17:08:01.315605
INFO:root:Sent report skynet220.45.18.4: skynet220.45.18.4, ping test, 50, Status: 201, Time: 2024-11-08 17:08:01.549339
INFO:root:Sent report fastdns6208.67.216.216: fastdns6208.67.216.216, ping test, 50, Status: 201, Time: 2024-11-08 17:08:01.551564
INFO:root:Sent report skynet1420.45.30.4: skynet1420.45.30.4, ping test, 50, Status: 201, Time: 2024-11-08 17:08:01.690067
INFO:root:Sent report fruittech1517.253.145.25: fruittech1517.253.145.25, ping test, 50, Status: 201, Time: 2024-11-08 17:08:01.699074
INFO:root:Sent report fruittech517.253.145.15: fruittech517.253.145.15, ping test, 50, Status: 201, Time: 2024-11-08 17:08:01.794919
INFO:root:Sent report fastdns5208.67.217.217: fastdns5208.67.217.217, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.004798
INFO:root:Sent report alphacorp148.8.14.14: alphacorp148.8.14.14, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.175684
INFO:root:Sent report alphacorp78.8.7.7: alphacorp78.8.7.7, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.393093
INFO:root:Sent report securecloud101.0.8.0: securecloud101.0.8.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.407281
INFO:root:Sent report cloudgiant913.248.127.2: cloudgiant913.248.127.2, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.407281
INFO:root:Sent report fruittech417.253.145.14: fruittech417.253.145.14, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.431222
INFO:root:Sent report cloudgiant313.248.121.2: cloudgiant313.248.121.2, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.445671
INFO:root:Sent report fastdns4208.67.218.218: fastdns4208.67.218.218, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.532361
INFO:root:Sent report fastdns13208.67.209.209: fastdns13208.67.209.209, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.532361
INFO:root:Sent report securecloud91.0.7.0: securecloud91.0.7.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.629759
INFO:root:Sent report fruittech1017.253.145.20: fruittech1017.253.145.20, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.632762
INFO:root:Sent report securecloud111.0.9.0: securecloud111.0.9.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.781393
INFO:root:Sent report alphacorp88.8.9.9: alphacorp88.8.9.9, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.831389
INFO:root:Sent report nextgen69.9.5.10: nextgen69.9.5.10, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.880448
INFO:root:Sent report fastdns7208.67.215.215: fastdns7208.67.215.215, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.883446
INFO:root:Sent report nextgen129.9.12.10: nextgen129.9.12.10, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.915117
INFO:root:Sent report skynet1220.45.28.4: skynet1220.45.28.4, ping test, 50, Status: 201, Time: 2024-11-08 17:08:02.986904
INFO:root:Sent report linuxhub6127.0.8.6: linuxhub6127.0.8.6, ping test, 100, Status: 201, Time: 2024-11-08 17:08:34.712051
INFO:root:Sent report loopback2127.0.0.3: loopback2127.0.0.3, ping test, 100, Status: 201, Time: 2024-11-08 17:08:35.543155
INFO:root:Sent report linuxhub7127.0.8.7: linuxhub7127.0.8.7, ping test, 100, Status: 201, Time: 2024-11-08 17:08:42.267289
INFO:root:Sent report cloudgiant413.248.122.2: cloudgiant413.248.122.2, ping test, 100, Status: 201, Time: 2024-11-08 17:08:48.891052
INFO:root:Sent report loopback5127.0.0.6: loopback5127.0.0.6, ping test, 100, Status: 201, Time: 2024-11-08 17:08:52.548444
INFO:root:Sent report alphacorp38.8.3.3: alphacorp38.8.3.3, ping test, 50, Status: 201, Time: 2024-11-08 17:08:53.773925
INFO:root:Sent report securecloud31.0.1.0: securecloud31.0.1.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:54.461297
INFO:root:Sent report securecloud51.0.3.0: securecloud51.0.3.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:55.116519
INFO:root:Sent report cloudgiant1413.248.132.2: cloudgiant1413.248.132.2, ping test, 100, Status: 201, Time: 2024-11-08 17:08:55.571581
INFO:root:Sent report fastdns6208.67.216.216: fastdns6208.67.216.216, ping test, 50, Status: 201, Time: 2024-11-08 17:08:55.846846
INFO:root:Sent report fruittech17.253.145.11: fruittech17.253.145.11, ping test, 50, Status: 201, Time: 2024-11-08 17:08:55.851345
INFO:root:Sent report alphacorp118.8.11.11: alphacorp118.8.11.11, ping test, 100, Status: 201, Time: 2024-11-08 17:08:56.017807
INFO:root:Sent report loopback4127.0.0.5: loopback4127.0.0.5, ping test, 100, Status: 201, Time: 2024-11-08 17:08:56.052791
INFO:root:Sent report cloudgiant1013.248.128.2: cloudgiant1013.248.128.2, ping test, 100, Status: 201, Time: 2024-11-08 17:08:56.095883
INFO:root:Sent report linuxhub8127.0.8.8: linuxhub8127.0.8.8, ping test, 100, Status: 201, Time: 2024-11-08 17:08:56.196392
INFO:root:Sent report cloudgiant13.248.119.2: cloudgiant13.248.119.2, ping test, 100, Status: 201, Time: 2024-11-08 17:08:56.675545
INFO:root:Sent report techsoft613.107.48.16: techsoft613.107.48.16, ping test, 100, Status: 201, Time: 2024-11-08 17:08:56.743170
INFO:root:Sent report techsoft813.107.50.16: techsoft813.107.50.16, ping test, 100, Status: 201, Time: 2024-11-08 17:08:56.840753
INFO:root:Sent report techsoft1013.107.52.16: techsoft1013.107.52.16, ping test, 100, Status: 201, Time: 2024-11-08 17:08:57.114604
INFO:root:Sent report fastdns5208.67.217.217: fastdns5208.67.217.217, ping test, 50, Status: 201, Time: 2024-11-08 17:08:57.347250
INFO:root:Sent report alphacorp58.8.1.1: alphacorp58.8.1.1, ping test, 100, Status: 201, Time: 2024-11-08 17:08:57.366097
INFO:root:Sent report loopback3127.0.0.4: loopback3127.0.0.4, ping test, 100, Status: 201, Time: 2024-11-08 17:08:57.397491
INFO:root:Sent report loopback6127.0.0.7: loopback6127.0.0.7, ping test, 100, Status: 201, Time: 2024-11-08 17:08:57.456244
INFO:root:Sent report fastdns9208.67.213.213: fastdns9208.67.213.213, ping test, 50, Status: 201, Time: 2024-11-08 17:08:57.482421
INFO:root:Sent report loopback9127.0.0.10: loopback9127.0.0.10, ping test, 100, Status: 201, Time: 2024-11-08 17:08:57.661374
INFO:root:Sent report linuxhub11127.0.8.11: linuxhub11127.0.8.11, ping test, 100, Status: 201, Time: 2024-11-08 17:08:57.757170
INFO:root:Sent report securecloud61.0.4.0: securecloud61.0.4.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:57.775301
INFO:root:Sent report linuxhub9127.0.8.9: linuxhub9127.0.8.9, ping test, 100, Status: 201, Time: 2024-11-08 17:08:57.999736
INFO:root:Sent report fastdns15208.67.207.207: fastdns15208.67.207.207, ping test, 100, Status: 201, Time: 2024-11-08 17:08:58.014921
INFO:root:Sent report securecloud81.0.6.0: securecloud81.0.6.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:58.024119
INFO:root:Sent report loopback12127.0.0.13: loopback12127.0.0.13, ping test, 100, Status: 201, Time: 2024-11-08 17:08:58.024119
INFO:root:Sent report alphacorp88.8.9.9: alphacorp88.8.9.9, ping test, 50, Status: 201, Time: 2024-11-08 17:08:58.075374
INFO:root:Sent report techsoft513.107.47.16: techsoft513.107.47.16, ping test, 50, Status: 201, Time: 2024-11-08 17:08:58.111914
INFO:root:Sent report securecloud151.0.13.0: securecloud151.0.13.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:58.382320
INFO:root:Sent report securecloud111.0.9.0: securecloud111.0.9.0, ping test, 50, Status: 201, Time: 2024-11-08 17:08:58.711620
INFO:root:Sent report alphacorp98.8.5.5: alphacorp98.8.5.5, ping test, 50, Status: 201, Time: 2024-11-08 17:08:58.794726
INFO:root:Sent report nextgen29.9.9.9: nextgen29.9.9.9, ping test, 100, Status: 201, Time: 2024-11-08 17:08:59.027616
INFO:root:Sent report fruittech417.253.145.14: fruittech417.253.145.14, ping test, 50, Status: 201, Time: 2024-11-08 17:08:59.210181
INFO:root:Sent report cloudgiant513.248.123.2: cloudgiant513.248.123.2, ping test, 50, Status: 201, Time: 2024-11-08 17:08:59.383346
INFO:root:Sent report nextgen79.9.4.10: nextgen79.9.4.10, ping test, 50, Status: 201, Time: 2024-11-08 17:08:59.474169
INFO:root:Sent report skynet820.45.24.4: skynet820.45.24.4, ping test, 50, Status: 201, Time: 2024-11-08 17:08:59.499850
INFO:root:Sent report cloudgiant913.248.127.2: cloudgiant913.248.127.2, ping test, 50, Status: 201, Time: 2024-11-08 17:08:59.773086
INFO:root:Sent report cloudgiant713.248.125.2: cloudgiant713.248.125.2, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.070418
INFO:root:Sent report skynet320.45.19.4: skynet320.45.19.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.251747
INFO:root:Sent report alphacorp108.8.10.10: alphacorp108.8.10.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.280390
INFO:root:Sent report fruittech1117.253.145.21: fruittech1117.253.145.21, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.457814
INFO:root:Sent report fruittech1517.253.145.25: fruittech1517.253.145.25, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.556390
INFO:root:Sent report skynet920.45.25.4: skynet920.45.25.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.615664
INFO:root:Sent report techsoft913.107.51.16: techsoft913.107.51.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.664039
INFO:root:Sent report cloudgiant613.248.124.2: cloudgiant613.248.124.2, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.812634
INFO:root:Sent report skynet1020.45.26.4: skynet1020.45.26.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:00.828522
INFO:root:Sent report fruittech217.253.145.12: fruittech217.253.145.12, ping test, 50, Status: 201, Time: 2024-11-08 17:09:01.160506
INFO:root:Sent report techsoft1113.107.53.16: techsoft1113.107.53.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:01.161509
INFO:root:Sent report alphacorp78.8.7.7: alphacorp78.8.7.7, ping test, 50, Status: 201, Time: 2024-11-08 17:09:01.193940
INFO:root:Sent report nextgen59.9.6.10: nextgen59.9.6.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:01.261911
INFO:root:Sent report fastdns7208.67.215.215: fastdns7208.67.215.215, ping test, 50, Status: 201, Time: 2024-11-08 17:09:01.277841
INFO:root:Sent report fruittech717.253.145.17: fruittech717.253.145.17, ping test, 50, Status: 201, Time: 2024-11-08 17:09:01.382062
INFO:root:Sent report techsoft1313.107.55.16: techsoft1313.107.55.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:01.805997
INFO:root:Sent report techsoft713.107.49.16: techsoft713.107.49.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:01.965288
INFO:root:Sent report skynet620.45.22.4: skynet620.45.22.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:02.108026
INFO:root:Sent report fruittech1017.253.145.20: fruittech1017.253.145.20, ping test, 50, Status: 201, Time: 2024-11-08 17:09:02.323355
INFO:root:Sent report skynet1520.45.31.4: skynet1520.45.31.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:02.429762
INFO:root:Sent report nextgen159.9.9.99: nextgen159.9.9.99, ping test, 50, Status: 201, Time: 2024-11-08 17:09:02.614881
INFO:root:Sent report nextgen99.9.2.10: nextgen99.9.2.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:02.810274
INFO:root:Sent report fastdns12208.67.210.210: fastdns12208.67.210.210, ping test, 50, Status: 201, Time: 2024-11-08 17:09:02.815272
INFO:root:Sent report skynet20.45.17.4: skynet20.45.17.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:02.851531
INFO:root:Sent report nextgen109.9.1.10: nextgen109.9.1.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:02.872291
INFO:root:Sent report skynet420.45.20.4: skynet420.45.20.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:03.049362
INFO:root:Sent report securecloud101.0.8.0: securecloud101.0.8.0, ping test, 50, Status: 201, Time: 2024-11-08 17:09:03.066579
INFO:root:Sent report fruittech617.253.145.16: fruittech617.253.145.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:03.156807
INFO:root:Sent report alphacorp148.8.14.14: alphacorp148.8.14.14, ping test, 50, Status: 201, Time: 2024-11-08 17:09:03.314633
INFO:root:Sent report fastdns8208.67.214.214: fastdns8208.67.214.214, ping test, 50, Status: 201, Time: 2024-11-08 17:09:04.353824
INFO:root:Sent report fruittech1217.253.145.22: fruittech1217.253.145.22, ping test, 50, Status: 201, Time: 2024-11-08 17:09:04.663660
INFO:root:Sent report fastdns3208.67.219.219: fastdns3208.67.219.219, ping test, 50, Status: 201, Time: 2024-11-08 17:09:05.336902
INFO:root:Sent report nextgen89.9.3.10: nextgen89.9.3.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:05.388645
INFO:root:Sent report fastdns11208.67.211.211: fastdns11208.67.211.211, ping test, 50, Status: 201, Time: 2024-11-08 17:09:06.253670
INFO:root:Sent report skynet1220.45.28.4: skynet1220.45.28.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:06.477139
INFO:root:Sent report nextgen9.9.9.10: nextgen9.9.9.10, ping test, 100, Status: 201, Time: 2024-11-08 17:09:06.532581
INFO:root:Sent report loopback8127.0.0.9: loopback8127.0.0.9, ping test, 100, Status: 201, Time: 2024-11-08 17:09:06.830096
INFO:root:Sent report securecloud21.1.1.1: securecloud21.1.1.1, ping test, 100, Status: 201, Time: 2024-11-08 17:09:06.961346
INFO:root:Sent report linuxhub2127.0.8.2: linuxhub2127.0.8.2, ping test, 100, Status: 201, Time: 2024-11-08 17:09:07.311136
INFO:root:Sent report loopback13127.0.0.14: loopback13127.0.0.14, ping test, 100, Status: 201, Time: 2024-11-08 17:09:07.446444
INFO:root:Sent report linuxhub4127.0.8.4: linuxhub4127.0.8.4, ping test, 100, Status: 201, Time: 2024-11-08 17:09:07.603858
INFO:root:Sent report linuxhub5127.0.8.5: linuxhub5127.0.8.5, ping test, 100, Status: 201, Time: 2024-11-08 17:09:07.703757
INFO:root:Sent report loopback15127.0.0.16: loopback15127.0.0.16, ping test, 100, Status: 201, Time: 2024-11-08 17:09:07.800501
INFO:root:Sent report linuxhub3127.0.8.3: linuxhub3127.0.8.3, ping test, 100, Status: 201, Time: 2024-11-08 17:09:07.910660
INFO:root:Sent report securecloud1.0.0.1: securecloud1.0.0.1, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.095913
INFO:root:Sent report cloudgiant1513.248.133.2: cloudgiant1513.248.133.2, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.165694
INFO:root:Sent report linuxhub14127.0.8.14: linuxhub14127.0.8.14, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.289354
INFO:root:Sent report fastdns2208.67.222.222: fastdns2208.67.222.222, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.380895
INFO:root:Sent report cloudgiant1213.248.130.2: cloudgiant1213.248.130.2, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.401019
INFO:root:Sent report alphacorp158.8.15.15: alphacorp158.8.15.15, ping test, 50, Status: 201, Time: 2024-11-08 17:09:08.428435
INFO:root:Sent report alphacorp8.8.4.4: alphacorp8.8.4.4, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.564572
INFO:root:Sent report cloudgiant213.248.120.2: cloudgiant213.248.120.2, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.647444
INFO:root:Sent report linuxhub13127.0.8.13: linuxhub13127.0.8.13, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.723297
INFO:root:Sent report techsoft1213.107.54.16: techsoft1213.107.54.16, ping test, 100, Status: 201, Time: 2024-11-08 17:09:08.958809
INFO:root:Sent report alphacorp28.8.8.8: alphacorp28.8.8.8, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.131843
INFO:root:Sent report loopback127.0.0.2: loopback127.0.0.2, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.258665
INFO:root:Sent report linuxhub15127.0.8.15: linuxhub15127.0.8.15, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.259665
INFO:root:Sent report techsoft13.107.43.16: techsoft13.107.43.16, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.386419
INFO:root:Sent report fastdns208.67.220.220: fastdns208.67.220.220, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.674676
INFO:root:Sent report linuxhub10127.0.8.10: linuxhub10127.0.8.10, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.693191
INFO:root:Sent report loopback10127.0.0.11: loopback10127.0.0.11, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.726329
INFO:root:Sent report cloudgiant1113.248.129.2: cloudgiant1113.248.129.2, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.743115
INFO:root:Sent report loopback11127.0.0.12: loopback11127.0.0.12, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.793679
INFO:root:Sent report linuxhub12127.0.8.12: linuxhub12127.0.8.12, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.877873
INFO:root:Sent report loopback7127.0.0.8: loopback7127.0.0.8, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.906282
INFO:root:Sent report cloudgiant1313.248.131.2: cloudgiant1313.248.131.2, ping test, 100, Status: 201, Time: 2024-11-08 17:09:09.910281
INFO:root:Sent report techsoft1413.107.56.16: techsoft1413.107.56.16, ping test, 100, Status: 201, Time: 2024-11-08 17:09:10.040310
INFO:root:Sent report loopback14127.0.0.15: loopback14127.0.0.15, ping test, 100, Status: 201, Time: 2024-11-08 17:09:10.051847
INFO:root:Sent report linuxhub127.0.8.1: linuxhub127.0.8.1, ping test, 100, Status: 201, Time: 2024-11-08 17:09:10.170243
INFO:root:Sent report alphacorp138.8.13.13: alphacorp138.8.13.13, ping test, 50, Status: 201, Time: 2024-11-08 17:09:12.420442
INFO:root:Sent report skynet1120.45.27.4: skynet1120.45.27.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:13.557808
INFO:root:Sent report securecloud91.0.7.0: securecloud91.0.7.0, ping test, 50, Status: 201, Time: 2024-11-08 17:09:14.258110
INFO:root:Sent report fruittech917.253.145.19: fruittech917.253.145.19, ping test, 50, Status: 201, Time: 2024-11-08 17:09:14.320388
INFO:root:Sent report skynet1320.45.29.4: skynet1320.45.29.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:16.306688
INFO:root:Sent report skynet220.45.18.4: skynet220.45.18.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:16.354764
INFO:root:Sent report fastdns10208.67.212.212: fastdns10208.67.212.212, ping test, 50, Status: 201, Time: 2024-11-08 17:09:16.544156
INFO:root:Sent report securecloud141.0.12.0: securecloud141.0.12.0, ping test, 50, Status: 201, Time: 2024-11-08 17:09:16.546164
INFO:root:Sent report nextgen149.9.10.10: nextgen149.9.10.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:16.821490
INFO:root:Sent report alphacorp68.8.6.6: alphacorp68.8.6.6, ping test, 50, Status: 201, Time: 2024-11-08 17:09:17.580487
INFO:root:Sent report fruittech317.253.145.13: fruittech317.253.145.13, ping test, 50, Status: 201, Time: 2024-11-08 17:09:17.736643
INFO:root:Sent report alphacorp128.8.12.12: alphacorp128.8.12.12, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.173798
INFO:root:Sent report cloudgiant313.248.121.2: cloudgiant313.248.121.2, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.225378
INFO:root:Sent report skynet1420.45.30.4: skynet1420.45.30.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.457313
INFO:root:Sent report fruittech1317.253.145.23: fruittech1317.253.145.23, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.459603
INFO:root:Sent report cloudgiant813.248.126.2: cloudgiant813.248.126.2, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.461603
INFO:root:Sent report fruittech1417.253.145.24: fruittech1417.253.145.24, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.465602
INFO:root:Sent report securecloud41.0.2.0: securecloud41.0.2.0, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.707213
INFO:root:Sent report techsoft213.107.44.16: techsoft213.107.44.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.762136
INFO:root:Sent report nextgen139.9.11.10: nextgen139.9.11.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.887632
INFO:root:Sent report techsoft313.107.45.16: techsoft313.107.45.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:18.923771
INFO:root:Sent report fastdns14208.67.208.208: fastdns14208.67.208.208, ping test, 50, Status: 201, Time: 2024-11-08 17:09:19.007359
INFO:root:Sent report skynet520.45.21.4: skynet520.45.21.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:19.085835
INFO:root:Sent report securecloud121.0.10.0: securecloud121.0.10.0, ping test, 50, Status: 201, Time: 2024-11-08 17:09:19.304329
INFO:root:Sent report nextgen39.9.8.10: nextgen39.9.8.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:19.319889
INFO:root:Sent report techsoft413.107.46.16: techsoft413.107.46.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:19.372278
INFO:root:Sent report alphacorp48.8.2.2: alphacorp48.8.2.2, ping test, 50, Status: 201, Time: 2024-11-08 17:09:19.424082
INFO:root:Sent report skynet720.45.23.4: skynet720.45.23.4, ping test, 50, Status: 201, Time: 2024-11-08 17:09:19.477086
INFO:root:Sent report fastdns4208.67.218.218: fastdns4208.67.218.218, ping test, 50, Status: 201, Time: 2024-11-08 17:09:20.055784
INFO:root:Sent report nextgen69.9.5.10: nextgen69.9.5.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:20.558557
INFO:root:Sent report nextgen119.9.0.10: nextgen119.9.0.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:20.726886
INFO:root:Sent report nextgen129.9.12.10: nextgen129.9.12.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:21.119942
INFO:root:Sent report fastdns13208.67.209.209: fastdns13208.67.209.209, ping test, 50, Status: 201, Time: 2024-11-08 17:09:21.956127
INFO:root:Sent report securecloud71.0.5.0: securecloud71.0.5.0, ping test, 50, Status: 201, Time: 2024-11-08 17:09:22.006943
INFO:root:Sent report nextgen49.9.7.10: nextgen49.9.7.10, ping test, 50, Status: 201, Time: 2024-11-08 17:09:22.376769
INFO:root:Sent report techsoft1513.107.57.16: techsoft1513.107.57.16, ping test, 50, Status: 201, Time: 2024-11-08 17:09:22.378772
INFO:root:Sent report fruittech817.253.145.18: fruittech817.253.145.18, ping test, 50, Status: 201, Time: 2024-11-08 17:09:22.385953
INFO:root:Sent report securecloud131.0.11.0: securecloud131.0.11.0, ping test, 50, Status: 201, Time: 2024-11-08 17:09:22.503802
INFO:root:Sent report fruittech517.253.145.15: fruittech517.253.145.15, ping test, 50, Status: 201, Time: 2024-11-08 17:09:22.731878
INFO:root:Sent report loopback127.0.0.2: loopback127.0.0.2, ping test, 100, Status: 201, Time: 2024-11-08 17:09:55.492218
INFO:root:Sent report alphacorp118.8.11.11: alphacorp118.8.11.11, ping test, 100, Status: 201, Time: 2024-11-08 17:09:55.501183
INFO:root:Sent report linuxhub8127.0.8.8: linuxhub8127.0.8.8, ping test, 100, Status: 201, Time: 2024-11-08 17:10:00.357295
INFO:root:Sent report techsoft1413.107.56.16: techsoft1413.107.56.16, ping test, 100, Status: 201, Time: 2024-11-08 17:10:03.056716
INFO:root:Sent report loopback3127.0.0.4: loopback3127.0.0.4, ping test, 100, Status: 201, Time: 2024-11-08 17:10:05.724923
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000282A7AC43B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BCEA443B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246DA5543E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013F7D8143B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019DF5E743B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002084C4943E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BD256843B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD6F6C43B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E279F943B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002918D5843B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000211102243B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023150D143B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DB092E43B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001555DC943B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E81D5943E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650EDA43B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D422C243B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025E995E43B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001478CC743B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000253002943B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AF560>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AFD70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D05F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D0E30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AF1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D1670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D1FA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D2930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D3D40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D3320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F07A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F26F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F3170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F3BC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB9100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB9B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EBA600>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EBB020>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EBBA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F11F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDCF80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F1C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDD9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB8680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDE450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDC530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDF920>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDEED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFC3E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFCE30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFD8B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F20260>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFED80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F20CE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F21760>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F22C30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F44140>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F44BC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F45640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F47560>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F46090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6C560>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6DF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFF7D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6E960>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6F3E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F888C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F89310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F89D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F883B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F23680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F46B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6D490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F221E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFE330>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6CA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F44CB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6CFE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6C2F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F46000>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6E210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F462D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6F9E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6D850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F47B30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F20350>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFEF00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F6C6B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F23BF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F230B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFCE90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F44EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F44500>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFD850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F213D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDF950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F202C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFE8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F21100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFFF50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDEED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDFAD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EFDC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB9910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB8D70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EBB680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB8380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F1610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F06B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F2780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EBAF90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738760F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDE1E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F35C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDD670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDCE90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D24E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D3680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F0B60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D2CF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D1550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D0140>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AFE90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D1AC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F885C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F88200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AE8A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F8A2A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D0F20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F3680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F7AB40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA9580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA8080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FAAA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F7B5C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F8B6B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FE1430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F79640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F78BF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA9FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA90A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F7A630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FAB4A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F78170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB9FA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F8AC60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FE3350>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024675002D20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467503CB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246750022A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FE28D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FE09B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024675000890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FE1E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024675003C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467503D010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467503C5F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024675024710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F89CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FE3DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FABF20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246750012E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024675026150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467503DA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246750270E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024675025190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024675003200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024675026660>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467503EA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467503EF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA83E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA9760>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FAA330>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA9940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F79DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F786E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F798B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F79280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F7B650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F79730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F89B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F8ABA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F895B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F88860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F88170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F893A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AD6D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738ADF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AE750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AD040>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F1CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D0E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D3410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AF950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738AFFB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D1C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F3D40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F1DC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D31A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA8E60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D3F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F3320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467385E8A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FAA240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738D3860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F11F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FAA4B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDD430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674FA9700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB92E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB9490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F7A3F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB9D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EBB560>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024673130200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467385FF80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDF2F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002467385F380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB83E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDDD30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F78290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EB97F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000246738F36B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDEF30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDD8B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674EDFA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:Error in send_data: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/post/reports (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024674F88FE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
